version: '3.8'

services:
  web:
    image: mijn-odoo-image
    env_file: .env
    depends_on:
      - db
      - mailpit # Wacht tot mailpit er is
    ports:
      - "8071:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - odoo-web-data:/var/lib/odoo
      - ./OttersDownload/Fotos:/mnt/images_source
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${ODOO_DB_PASSWORD}

  db:
    image: postgres:18
    env_file: .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD}
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql
    ports:
      - "5444:5432"

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/database.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - ./mailpit-data:/data

volumes:
  odoo-db-data:
  odoo-web-data: