version: '3.8'

services:
  web:
    image: odoo:19.0
    env_file: .env
    depends_on:
      - db
    ports:
      - "8071:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${ODOO_DB_PASSWORD}
  db:
    image: postgres:18
    env_file: .env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD} # Moet matchen met Odoo's PASSWORD
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql
    ports:
      - "5444:5432"
  # === NIEUWE SERVICE ===
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Web interface
      - "1025:1025"  # SMTP poort

volumes:
  odoo-db-data:
  odoo-web-data:
